config/routes.rb
Rails.application.routes.draw do
  resources :favorite_pets
  get 'home/index'
  root 'home#index'
  resources :users do 
    post 'sign_in', on: :collection
    get 'favorite_pets'
  end
  resources :pets do
    post 'add_favorite'
    delete 'remove_favorite'
  end
end

app/models/favorite_pet.rb
class FavoritePet < ActiveRecord::Base
	belongs_to :pet
	belongs_to :user
end

app/models/pet.rb
class Pet < ActiveRecord::Base
	has_many :favorite_pets
	belongs_to :user
	attr_accessor :is_favorite
	attr_accessor :image_url

	has_attached_file :image
	validates_attachment :image, content_type: { content_type: "image/jpeg" }

end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :favorite_pets
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  skip_before_action :verify_authenticity_token, if: :json_request?

  protected

  def json_request?
    request.format.json?
  end
end

app/controllers/favorite_pets_controller.rb
class FavoritePetsController < ApplicationController
  before_action :set_favorite_pet, only: [:show, :edit, :update, :destroy]

  # GET /favorite_pets
  # GET /favorite_pets.json
  def index
    @favorite_pets = FavoritePet.all
  end

  # GET /favorite_pets/1
  # GET /favorite_pets/1.json
  def show
  end

  # GET /favorite_pets/new
  def new
    @favorite_pet = FavoritePet.new
  end

  # GET /favorite_pets/1/edit
  def edit
  end

  # POST /favorite_pets
  # POST /favorite_pets.json
  def create
    @favorite_pet = FavoritePet.new(favorite_pet_params)

    respond_to do |format|
      if @favorite_pet.save
        format.html { redirect_to @favorite_pet, notice: 'Favorite pet was successfully created.' }
        format.json { render :show, status: :created, location: @favorite_pet }
      else
        format.html { render :new }
        format.json { render json: @favorite_pet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /favorite_pets/1
  # PATCH/PUT /favorite_pets/1.json
  def update
    respond_to do |format|
      if @favorite_pet.update(favorite_pet_params)
        format.html { redirect_to @favorite_pet, notice: 'Favorite pet was successfully updated.' }
        format.json { render :show, status: :ok, location: @favorite_pet }
      else
        format.html { render :edit }
        format.json { render json: @favorite_pet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /favorite_pets/1
  # DELETE /favorite_pets/1.json
  def destroy
    @favorite_pet.destroy
    respond_to do |format|
      format.html { redirect_to favorite_pets_url, notice: 'Favorite pet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_favorite_pet
      @favorite_pet = FavoritePet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def favorite_pet_params
      params.require(:favorite_pet).permit(:pet_id, :user_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  before_action :set_pet, only: [:show, :edit, :update, :destroy]

  # GET /pets
  # GET /pets.json
  def index
    @user = User.find_by(id: params[:user_id])
    @pets = Pet.all.each do |x| 
      x.is_favorite = ( FavoritePet.exists?(user_id: @user.nil? ? nil : @user.id, pet_id: x.id) )
      x.image_url = request.base_url + x.image.url
   end

   puts 'this'
   puts request.base_url

  end

  # GET /pets/1
  # GET /pets/1.json
  def show
  end

  # GET /pets/new
  def new
    @pet = Pet.new
  end

  # GET /pets/1/edit
  def edit
  end

  # POST /pets
  # POST /pets.json
  def create
    @pet = Pet.new(pet_params)

    respond_to do |format|
      if @pet.save
        format.html { redirect_to @pet, notice: 'Pet was successfully created.' }
        format.json { render :show, status: :created, location: @pet }
      else
        format.html { render :new }
        format.json { render json: @pet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pets/1
  # PATCH/PUT /pets/1.json
  def update
    respond_to do |format|
      if @pet.update(pet_params)
        format.html { redirect_to @pet, notice: 'Pet was successfully updated.' }
        format.json { render :show, status: :ok, location: @pet }
      else
        format.html { render :edit }
        format.json { render json: @pet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pets/1
  # DELETE /pets/1.json
  def destroy
    @pet.destroy
    respond_to do |format|
      format.html { redirect_to pets_url, notice: 'Pet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def add_favorite
    @favorite_pet = FavoritePet.find_or_initialize_by(user_id: params[:user_id], pet_id: params[:pet_id])
    @favorite_pet.save
    @pet = Pet.find_by(id: @favorite_pet.pet_id)
    @pet.is_favorite = true
    @user = User.find_by(id: @favorite_pet.user_id)
    render 'pets/show', location: @pet
  end

  def remove_favorite
    @favorite_pet = FavoritePet.find_by(user_id: params[:user_id], pet_id: params[:pet_id])
    @pet = Pet.find_by(id: @favorite_pet.pet_id)
    @pet.is_favorite = false
    @user = User.find_by(id: @favorite_pet.user_id)
    @favorite_pet.delete
    render 'pets/show', location: @pet
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pet
      @pet = Pet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pet_params
      params.require(:pet).permit(:name, :family, :user_id, :image_url, :image)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def sign_in
    @user = User.find_by(email: params[:email], password: params[:password])
    respond_to do |format|
      unless @user.nil?
        # format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :ok, location: @user }
      else
        # format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(update_user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def favorite_pets
    @user = User.find(params[:user_id])
    @pets = Pet.joins("JOIN favorite_pets ON pets.id = favorite_pets.pet_id").where("favorite_pets.user_id = ?", @user.id)
    render 'pets/index'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :password)
    end

    def update_user_params
      params.require(:user).permit(:first_name, :last_name, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorite_pets_helper.rb
module FavoritePetsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/favorite_pets/_form.html.erb
<%= form_for(@favorite_pet) do |f| %>
  <% if @favorite_pet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@favorite_pet.errors.count, "error") %> prohibited this favorite_pet from being saved:</h2>

      <ul>
      <% @favorite_pet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :pet_id %><br>
    <%= f.number_field :pet_id %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/favorite_pets/edit.html.erb
<h1>Editing Favorite Pet</h1>

<%= render 'form' %>

<%= link_to 'Show', @favorite_pet %> |
<%= link_to 'Back', favorite_pets_path %>

app/views/favorite_pets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Favorite Pets</h1>

<table>
  <thead>
    <tr>
      <th>Pet</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @favorite_pets.each do |favorite_pet| %>
      <tr>
        <td><%= favorite_pet.pet_id %></td>
        <td><%= favorite_pet.user_id %></td>
        <td><%= link_to 'Show', favorite_pet %></td>
        <td><%= link_to 'Edit', edit_favorite_pet_path(favorite_pet) %></td>
        <td><%= link_to 'Destroy', favorite_pet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Favorite pet', new_favorite_pet_path %>

app/views/favorite_pets/new.html.erb
<h1>New Favorite Pet</h1>

<%= render 'form' %>

<%= link_to 'Back', favorite_pets_path %>

app/views/favorite_pets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Pet:</strong>
  <%= @favorite_pet.pet_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @favorite_pet.user_id %>
</p>

<%= link_to 'Edit', edit_favorite_pet_path(@favorite_pet) %> |
<%= link_to 'Back', favorite_pets_path %>

app/views/home/index.html.erb
<h1>PETS TK</h1>

<p>List of sources</p>

<ul>
	<li><%= link_to "Pets", pets_path %></li>
	<li><%= link_to "Users", users_path %></li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PetsTkApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pets/_form.html.erb
<%= form_for(@pet) do |f| %>
  <% if @pet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pet.errors.count, "error") %> prohibited this pet from being saved:</h2>

      <ul>
      <% @pet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :family %><br>
    <%= f.text_field :family %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pets/edit.html.erb
<h1>Editing Pet</h1>

<%= render 'form' %>

<%= link_to 'Show', @pet %> |
<%= link_to 'Back', pets_path %>

app/views/pets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Pets</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Family</th>
      <th>User ID</th>
      <th>Image url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pets.each do |pet| %>
      <tr>
        <td><%= pet.name %></td>
        <td><%= pet.family %></td>
        <td><%= pet.user_id %></td>
        <td><%= pet.image.url %></td>
        <td><%= link_to 'Show', pet %></td>
        <td><%= link_to 'Edit', edit_pet_path(pet) %></td>
        <td><%= link_to 'Destroy', pet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pet', new_pet_path %>

app/views/pets/new.html.erb
<h1>New Pet</h1>

<%= render 'form' %>

<%= link_to 'Back', pets_path %>

app/views/pets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @pet.name %>
</p>

<p>
  <strong>Family:</strong>
  <%= @pet.family %>
</p>

<p>
  <strong>User ID:</strong>
  <%= @pet.user_id %>
</p>

<p>
  <strong>Image url:</strong>
	<%= image_tag @pet.image.url, width: 200 %>
</p>

<%= link_to 'Edit', edit_pet_path(@pet) %> |
<%= link_to 'Back', pets_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Email</th>
      <th>Password</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= user.email %></td>
        <td><%= user.password %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @user.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @user.last_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Password:</strong>
  <%= @user.password %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>